.TH DEVLINK\-DEV 8 "14 Mar 2016" "iproute2" "Linux"
.SH NAME
devlink-dev \- devlink device configuration
.SH SYNOPSIS
.sp
.ad l
.in +8
.ti -8
.B devlink
.RI "[ " OPTIONS " ]"
.B dev
.RI  " { " COMMAND " | "
.BR help " }"
.sp

.ti -8
.IR OPTIONS " := { "
\fB\-V\fR[\fIersion\fR] |
\fB\-n\fR[\fIno-nice-names\fR] }

.ti -8
.B devlink dev show
.RI "[ " DEV " ]"

.ti -8
.B devlink dev help

.ti -8
.BR "devlink dev eswitch set"
.IR DEV
.RI "[ "
.BR mode " { " legacy " | " switchdev " } "
.RI "]"
.RI "[ "
.BR inline-mode " { " none " | " link " | " network " | " transport " } "
.RI "]"
.RI "[ "
.BR encap " { " disable " | " enable " } "
.RI "]"

.ti -8
.BR "devlink dev eswitch show"
.IR DEV

.SH "DESCRIPTION"
.SS devlink dev show - display devlink device attributes

.PP
.I "DEV"
- specifies the devlink device to show.
If this argument is omitted all devices are listed.

.in +4
Format is:
.in +2
BUS_NAME/BUS_ADDRESS

.SS devlink dev eswitch show - display devlink device eswitch attributes
.SS devlink dev eswitch set  - sets devlink device eswitch attributes

.TP
.BR mode " { " legacy " | " switchdev " } "
Set eswitch mode

.I legacy
- Legacy SRIOV

.I switchdev
- SRIOV switchdev offloads

.TP
.BR inline-mode " { " none " | " link " | " network " | " transport " } "
Some HWs need the VF driver to put part of the packet headers on the TX descriptor so the e-switch can do proper matching and steering.

.I none
- None

.I link
- L2 mode

.I network
- L3 mode

.I transport
- L4 mode

.TP
.BR encap " { " disable " | " enable " } "
Set eswitch encapsulation support

.I disable
- Disable encapsulation support

.I enable
- Enable encapsulation support

.SH "EXAMPLES"
.PP
devlink dev show
.RS 4
Shows the state of all devlink devices on the system.
.RE
.PP
devlink dev show pci/0000:01:00.0
.RS 4
Shows the state of specified devlink device.
.RE
.PP
devlink dev eswitch show pci/0000:01:00.0
.RS 4
Shows the eswitch mode of specified devlink device.
.RE
.PP
devlink dev eswitch set pci/0000:01:00.0 mode switchdev
.RS 4
Sets the eswitch mode of specified devlink device to switchdev.

.SH SEE ALSO
.BR devlink (8),
.BR devlink-port (8),
.BR devlink-sb (8),
.BR devlink-monitor (8),
.br

.SH AUTHOR
Jiri Pirko <jiri@mellanox.com>
